name: Unami Lodge, One
title: Unami Lodge, One
logo: "/img/logo.png"
description: "As the founding lodge of the Order of the Arrow, Unami Lodge, One serves as the chapter of Scouting’s National Honor Society for the Cradle of Liberty Council. Unami exists to serve the units, community, and camps of the Cradle of Liberty."

alert:
  text: <strong>Both Community Service Day projects have been postponed</strong> due to weather related concerns. Stay safe and dry this weekend!
  class: alert-primary # (Default is alert-primary)

plugins:
  - jekyll-paginate-v2
  - jekyll_picture_tag
  - jekyll/minibundle

url: http://127.0.0.1:4000
baseurl:

picture:
  nomarkdown: false

recaptcha: 6LdlwroUAAAAAKKNaJmAUiIKTRFYNk_qVpy9b5Fo

permalink: /news/:title

pagination:
  enabled: true
  per_page: 9
  permalink: '/:num/'
  title: 'News - Page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

page_gen:
  - data: 'chapters'
    template: 'chapters'
    name: 'email'
    dir: 'chapters'
